#!/bin/bash
# Makes the public pack (original content, CC0) and zips it for the page: web/demo-pack.zip
set -e
cd "$(dirname "$0")"
rm -rf ../../public-pack
python3 gen_map.py
python3 gen_bus.py
python3 gen_base.py
cat > ../../public-pack/LICENSE.txt <<'TXT'
openOMSI public demo pack
=========================
Every file in this pack - the map, the buses, the scenery, the textures, the scripts - was
generated by the code in tools/public from nothing but that code. It contains nothing of OMSI 2
or of any other game.

To the extent possible under law the author has dedicated all of it to the public domain
(CC0 1.0 Universal, https://creativecommons.org/publicdomain/zero/1.0/).
TXT
cd ../..
python3 - <<'PY'
import os, zipfile
src, out = 'public-pack', 'web/demo-pack.zip'
n = 0
with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for dp, _, fs in os.walk(src):
        for f in sorted(fs):
            p = os.path.join(dp, f)
            z.write(p, os.path.relpath(p, src)); n += 1
print(n, 'files ->', out, round(os.path.getsize(out) / 1e6, 2), 'MB')
PY
